[package]
name = "serde_box"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metatype = "0.2.0"
serde = { version = "1.0.125", features = ["derive"] }
erased-serde = "0.3.13"
dashmap = "4.0.2"
